const { test } = require("node:test")
const assert = require("node:assert/strict")
const { commitProject } = require("./_runtime.cjs")

test("部分暂存检查失败：暂存区与未暂存内容均保持原样", (t) => {
    const p = commitProject(t)
    p.write("src/bad.ts", "const count: = ;\n")
    p.git("add", "--", "src/bad.ts")
    p.write("src/bad.ts", "const count: = ;\n// UNSTAGED_ONLY\n")
    const staged = p.git("diff", "--cached", "--binary")
    const unstaged = p.git("diff", "--binary")
    const head = p.git("rev-parse", "HEAD")
    const result = p.commit()
    assert.notEqual(result.status, 0)
    assert.equal(p.git("rev-parse", "HEAD"), head)
    assert.equal(p.git("diff", "--cached", "--binary"), staged)
    assert.equal(p.git("diff", "--binary"), unstaged)
    assert.equal(p.git("stash", "list"), "")
})
